version: '3.9'

services:
  mongo:
    container_name: mongodb
    image: mongodb/mongodb-community-server:7.0.4-ubuntu2204
    networks:
      - my-network
    restart: unless-stopped
    ports:
      - 27017:27017

    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=pA55vv0Rd
    volumes:
      - "mongodb_data:/data/db"

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-18-alpine3.18
    networks:
      - my-network
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pA55vv0Rd
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
# more themes here: http://codemirror.net/demo/theme.html
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=ali
      - ME_CONFIG_BASICAUTH_PASSWORD=pA55vv0Rd

volumes:
  mongodb_data:
    driver: local

networks:
  my-network:
    driver: bridge

